/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include<string>

/* Header for class com_example_xiaoentest_NativeInterfaceTools */

#ifndef _Included_com_example_xiaoentest_NativeInterfaceTools
#define _Included_com_example_xiaoentest_NativeInterfaceTools
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_xiaoentest_NativeInterfaceTools
 * Method:    getTextFromNative
 * Signature: ()Ljava/lang/String;
 */
#include "com_example_xiaoentest_NativeInterfaceTools.h"
JNIEXPORT jstring JNICALL Java_com_example_xiaoentest_NativeInterfaceTools_getTextFromNative
  (JNIEnv *env, jclass jobj){
  return env->NewStringUTF("hello wordffffff");
  }

#ifdef __cplusplus
}
#endif
#endif
