/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_xiaoentest_NativeInterfaceTools */

#ifndef _Included_com_example_xiaoentest_NativeInterfaceTools
#define _Included_com_example_xiaoentest_NativeInterfaceTools
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_xiaoentest_NativeInterfaceTools
 * Method:    getTextFromNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_xiaoentest_NativeInterfaceTools_getTextFromNative
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
